version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: webpack-cli
    versions:
    - "> 3.3.12"
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.15
    - 7.13.8
  - dependency-name: "@wordpress/icons"
    versions:
    - 2.10.1
    - 2.9.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.13.13
    - 7.13.15
    - 7.13.8
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.21.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.2
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.2
    - 5.2.1
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.9
    - 1.4.1
  - dependency-name: webpack
    versions:
    - 5.31.2
  - dependency-name: classnames
    versions:
    - 2.3.1
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.4.0
    - 17.4.1
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.13.8
  - dependency-name: "@babel/plugin-transform-async-to-generator"
    versions:
    - 7.13.0
  - dependency-name: "@babel/plugin-transform-react-jsx"
    versions:
    - 7.12.13
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
  - dependency-name: postcss-loader
    versions:
    - 4.2.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
