site_name: 'Guttenberg Blocks'
theme:
  name: 'material'
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: cyan
  features:
    - toc.integrate
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
#   - javascripts/config.js
extra_css:
  - stylesheets/extra.css
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/github.min.css
